on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Setup yarn
        run: npm update -g yarn

      - name: Generate lockfile
        run: yarn install --mode update-lockfile

      - name: Find cache
        uses: actions/cache@v3
        id: yarn_cache
        env:
          cache-name: cache-yarn
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: ${{ steps.yarn_cache.outputs.cache-hit != 'true' }}
        run: yarn install
        env:
          NODE_ENV: production

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: blog.sevenc7c.com
